// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: movies_people_service_v1_messages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMoviePeopleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeopleIDs string `protobuf:"bytes,1,opt,name=PeopleIDs,json=people_ids,proto3" json:"PeopleIDs,omitempty"`
}

func (x *GetMoviePeopleRequest) Reset() {
	*x = GetMoviePeopleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_people_service_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoviePeopleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviePeopleRequest) ProtoMessage() {}

func (x *GetMoviePeopleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movies_people_service_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviePeopleRequest.ProtoReflect.Descriptor instead.
func (*GetMoviePeopleRequest) Descriptor() ([]byte, []int) {
	return file_movies_people_service_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetMoviePeopleRequest) GetPeopleIDs() string {
	if x != nil {
		return x.PeopleIDs
	}
	return ""
}

type Human struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	FullnameRU string `protobuf:"bytes,2,opt,name=fullnameRU,json=fullname_ru,proto3" json:"fullnameRU,omitempty"`
	FullnameEN string `protobuf:"bytes,3,opt,name=fullnameEN,json=fullname_en,proto3" json:"fullnameEN,omitempty"`
	Birthday   string `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Sex        string `protobuf:"bytes,5,opt,name=sex,proto3" json:"sex,omitempty"`
	PhotoUrl   string `protobuf:"bytes,6,opt,name=photoUrl,json=photo_url,proto3" json:"photoUrl,omitempty"`
}

func (x *Human) Reset() {
	*x = Human{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_people_service_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Human) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Human) ProtoMessage() {}

func (x *Human) ProtoReflect() protoreflect.Message {
	mi := &file_movies_people_service_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Human.ProtoReflect.Descriptor instead.
func (*Human) Descriptor() ([]byte, []int) {
	return file_movies_people_service_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Human) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Human) GetFullnameRU() string {
	if x != nil {
		return x.FullnameRU
	}
	return ""
}

func (x *Human) GetFullnameEN() string {
	if x != nil {
		return x.FullnameEN
	}
	return ""
}

func (x *Human) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *Human) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Human) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

type Humans struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	People map[string]*Human `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Humans) Reset() {
	*x = Humans{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_people_service_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Humans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Humans) ProtoMessage() {}

func (x *Humans) ProtoReflect() protoreflect.Message {
	mi := &file_movies_people_service_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Humans.ProtoReflect.Descriptor instead.
func (*Humans) Descriptor() ([]byte, []int) {
	return file_movies_people_service_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Humans) GetPeople() map[string]*Human {
	if x != nil {
		return x.People
	}
	return nil
}

type UserErrorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UserErrorMessage) Reset() {
	*x = UserErrorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_people_service_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserErrorMessage) ProtoMessage() {}

func (x *UserErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_movies_people_service_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserErrorMessage.ProtoReflect.Descriptor instead.
func (*UserErrorMessage) Descriptor() ([]byte, []int) {
	return file_movies_people_service_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UserErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_movies_people_service_v1_messages_proto protoreflect.FileDescriptor

var file_movies_people_service_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x73, 0x5f, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x36, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x65, 0x6f, 0x70,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x09, 0x50, 0x65, 0x6f,
	0x70, 0x6c, 0x65, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x65,
	0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x05, 0x48, 0x75, 0x6d,
	0x61, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x55,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65,
	0x5f, 0x72, 0x75, 0x12, 0x1f, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x45,
	0x4e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d,
	0x65, 0x5f, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73,
	0x65, 0x78, 0x12, 0x1b, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x72, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x22,
	0xa4, 0x01, 0x0a, 0x06, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x73, 0x12, 0x41, 0x0a, 0x06, 0x70, 0x65,
	0x6f, 0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x73, 0x5f, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x73, 0x2e, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x1a, 0x57, 0x0a,
	0x0b, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x32,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2c, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x70,
	0x65, 0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_movies_people_service_v1_messages_proto_rawDescOnce sync.Once
	file_movies_people_service_v1_messages_proto_rawDescData = file_movies_people_service_v1_messages_proto_rawDesc
)

func file_movies_people_service_v1_messages_proto_rawDescGZIP() []byte {
	file_movies_people_service_v1_messages_proto_rawDescOnce.Do(func() {
		file_movies_people_service_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_movies_people_service_v1_messages_proto_rawDescData)
	})
	return file_movies_people_service_v1_messages_proto_rawDescData
}

var file_movies_people_service_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_movies_people_service_v1_messages_proto_goTypes = []interface{}{
	(*GetMoviePeopleRequest)(nil), // 0: movies_people_service.GetMoviePeopleRequest
	(*Human)(nil),                 // 1: movies_people_service.Human
	(*Humans)(nil),                // 2: movies_people_service.Humans
	(*UserErrorMessage)(nil),      // 3: movies_people_service.UserErrorMessage
	nil,                           // 4: movies_people_service.Humans.PeopleEntry
}
var file_movies_people_service_v1_messages_proto_depIdxs = []int32{
	4, // 0: movies_people_service.Humans.people:type_name -> movies_people_service.Humans.PeopleEntry
	1, // 1: movies_people_service.Humans.PeopleEntry.value:type_name -> movies_people_service.Human
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_movies_people_service_v1_messages_proto_init() }
func file_movies_people_service_v1_messages_proto_init() {
	if File_movies_people_service_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_movies_people_service_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoviePeopleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movies_people_service_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Human); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movies_people_service_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Humans); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movies_people_service_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserErrorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_movies_people_service_v1_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_movies_people_service_v1_messages_proto_goTypes,
		DependencyIndexes: file_movies_people_service_v1_messages_proto_depIdxs,
		MessageInfos:      file_movies_people_service_v1_messages_proto_msgTypes,
	}.Build()
	File_movies_people_service_v1_messages_proto = out.File
	file_movies_people_service_v1_messages_proto_rawDesc = nil
	file_movies_people_service_v1_messages_proto_goTypes = nil
	file_movies_people_service_v1_messages_proto_depIdxs = nil
}
